import { formatFeedbackDate, formatUsd } from "./feedback";
import {
  type EvidenceRef,
  type FeedbackReport,
  type KbRef,
  RECOMMENDATION_TYPE_LABEL,
  SIGNAL_KINDS,
  SIGNAL_LABEL,
} from "./feedback-report";

// Export a stored QA report as a shareable document. Two formats, both built from
// the same persisted report so a download is just a render (no model calls):
//   • Markdown — the full readable report, for pasting into Notion/Docs/a ticket.
//   • CSV      — one row per recommendation, a worklist the customer-education team
//                can assign and track while improving the KB.
// `baseUrl` (the request origin) absolutizes the in-app evidence links so they
// stay clickable outside the app; KB article URLs are already absolute.

function absolutize(href: string, baseUrl: string): string {
  if (/^https?:\/\//i.test(href)) return href;
  return `${baseUrl.replace(/\/$/, "")}${href.startsWith("/") ? "" : "/"}${href}`;
}

function statLine(report: FeedbackReport): string[] {
  const s = report.stats;
  const byKind = SIGNAL_KINDS.filter((k) => s.byKind[k] > 0)
    .map((k) => `${SIGNAL_LABEL[k]} ${s.byKind[k]}`)
    .join(", ");
  const reasons = s.flagsByReason.map((r) => `${r.reason} ${r.count}`).join(", ");
  return [
    `- **Negative signals:** ${s.totalSignals}`,
    `- **Hallucinations:** ${s.hallucinationCount}`,
    `- **Avg groundedness (judged):** ${s.avgGroundednessJudged == null ? "—" : s.avgGroundednessJudged.toFixed(2)}`,
    `- **Wrong-answer spend:** ${formatUsd(s.negativeSignalCost)}`,
    byKind ? `- **By signal:** ${byKind}` : "",
    `- **Human signal:** ${s.thumbsUp} 👍 / ${s.thumbsDown} 👎 · ${s.expertEdits} expert edits`,
    reasons ? `- **Flag reasons:** ${reasons}` : "",
  ].filter(Boolean);
}

function kbLines(refs: ReadonlyArray<KbRef>): string[] {
  return refs.map((r) => `  - [${r.title}](${r.url})${r.score != null ? ` _(${r.score.toFixed(2)})_` : ""}`);
}

function evidenceLines(refs: ReadonlyArray<EvidenceRef>, baseUrl: string): string[] {
  return refs.map((e) => `  - [${e.label}](${absolutize(e.href, baseUrl)})`);
}

export function reportToMarkdown(report: FeedbackReport, baseUrl: string): string {
  const lines: string[] = [];
  lines.push("# Clever Support — QA Report");
  lines.push("");
  lines.push(
    `_Generated ${formatFeedbackDate(report.generatedAt)} · last ${report.windowDays} days · ${report.model}_`,
  );
  lines.push("");

  lines.push("## Health");
  lines.push("");
  lines.push(report.health.summary);
  if (report.health.trend) {
    lines.push("");
    lines.push(`_${report.health.trend}_`);
  }
  lines.push("");

  lines.push("## At a glance");
  lines.push("");
  lines.push(...statLine(report));
  lines.push("");

  if (report.recommendations.length > 0) {
    lines.push("## Recommendations");
    lines.push("");
    for (const rec of report.recommendations) {
      lines.push(`### ${rec.rank}. ${rec.title}`);
      lines.push("");
      lines.push(
        `**Type:** ${RECOMMENDATION_TYPE_LABEL[rec.type]} · **Severity:** ${rec.severity}${rec.themeTitle ? ` · **Theme:** ${rec.themeTitle}` : ""}`,
      );
      lines.push("");
      lines.push(rec.rationale);
      lines.push("");
      lines.push(`**Action:** ${rec.action}`);
      if (rec.kbRefs.length > 0) {
        lines.push("");
        lines.push("**KB articles:**");
        lines.push(...kbLines(rec.kbRefs));
      }
      if (rec.evidence.length > 0) {
        lines.push("");
        lines.push("**Evidence:**");
        lines.push(...evidenceLines(rec.evidence, baseUrl));
      }
      lines.push("");
    }
  }

  if (report.themes.length > 0) {
    lines.push("## Themes");
    lines.push("");
    for (const t of report.themes) {
      lines.push(`### ${t.title} — ${t.count} signal${t.count === 1 ? "" : "s"}`);
      lines.push("");
      if (t.description) {
        lines.push(t.description);
        lines.push("");
      }
      lines.push(`KB coverage: **${t.kbCoverage.confidence}**`);
      if (t.kbCoverage.articles.length > 0) {
        lines.push("");
        lines.push(...kbLines(t.kbCoverage.articles));
      }
      if (t.evidence.length > 0) {
        lines.push("");
        lines.push("Evidence:");
        lines.push(...evidenceLines(t.evidence, baseUrl));
      }
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("");
  lines.push("_Generated by the Clever Support QA analyst. Evidence links open the flagged thread or inquiry in the app._");
  lines.push("");
  return lines.join("\n");
}

// RFC-4180 field: wrap in quotes, double internal quotes.
function csvField(value: string | number): string {
  const s = String(value ?? "");
  return `"${s.replace(/"/g, '""')}"`;
}

export function reportToCsv(report: FeedbackReport, baseUrl: string): string {
  const header = [
    "Priority",
    "Type",
    "Severity",
    "Recommendation",
    "Action",
    "Theme",
    "KB articles",
    "Evidence",
  ];
  const rows = report.recommendations.map((rec) =>
    [
      rec.rank,
      RECOMMENDATION_TYPE_LABEL[rec.type],
      rec.severity,
      rec.title,
      rec.action,
      rec.themeTitle ?? "",
      rec.kbRefs.map((r) => r.url).join(" | "),
      rec.evidence.map((e) => absolutize(e.href, baseUrl)).join(" | "),
    ]
      .map(csvField)
      .join(","),
  );
  // CRLF line endings + a UTF-8 BOM so Excel opens it cleanly.
  return `﻿${[header.map(csvField).join(","), ...rows].join("\r\n")}\r\n`;
}

// e.g. clever-qa-report-2026-06-30.md — date from the report, slug-safe.
export function exportFilename(report: FeedbackReport, ext: "md" | "csv"): string {
  const day = report.generatedAt.slice(0, 10); // YYYY-MM-DD from the ISO string
  return `clever-qa-report-${day}.${ext}`;
}
